artifacts_root: d:/deep_learning/chicken_dieases_classification/artifacts

data_ingestion:
  root_dir: d:/deep_learning/chicken_dieases_classification/artifacts/data_ingestion
  source_URL: https://github.com/entbappy/Branching-tutorial/raw/master/Chicken-fecal-images.zip
  local_data_file: d:/deep_learning/chicken_dieases_classification/artifacts/data_ingestion/chicken-diseases-image-dataset.zip
  unzipped_data_dir: d:/deep_learning/chicken_dieases_classification/artifacts/data_ingestion/chicken-diseases-image-dataset


prepare_base_model:
  root_dir: d:/deep_learning/chicken_dieases_classification/artifacts/prepare_base_model
  base_model_path: d:/deep_learning/chicken_dieases_classification/artifacts/prepare_base_model/base_model.h5
  updated_base_model_path: d:/deep_learning/chicken_dieases_classification/artifacts/prepare_base_model/updated_base_model.h5
  params:
    IMG_SIZE: [224, 224]
    CLASS_COUNT: 3
    BASE_MODEL_TRAINABLE: False
    DROPOUT_RATE: 0.5